### ISSUE TITLE
Not really an issue but I'm curious, what steps did you do to make honeygain 0.8.0 work with box64?

### ISSUE THREAD

**Issue by Abdalnablse10** [DevonTM/honeygain-arm64#1]

**Comment by Abdalnablse10** [comment]
And i would love to hear about unsuccessful attempts.

**Comment by DevonTM** [comment]
Sorry, but this is not actually working; it keeps crashing when run with box64. By the way, Honeygain 0.8.1 has already been released, and it now supports arm64 natively.
