### ISSUE TITLE
Error Processing Authorisation

### ISSUE THREAD

**Issue by Craigy117** [DevonTM/honeygain-arm64#2]
So it might because I'm running on a Pi3 but I am getting this response within docker when trying to run the container: 

"TOU are accepted
Error processing authorisation
Box64: honeygain crashed... restarting in 30 seconds"

Have you come across this before?

Running Raspberry Pi Os Legacy (64bit) on a Raspberry Pi 3 Model B.

I read that the processor architecture of aarch64 is the same as ARM64, is that correct? Forgive my ignorance

**Comment by DevonTM** [comment]
Yeah, aarch64 is arm64. This repository is now archived. You can try the official release of Honeygain 0.8.1, which officially supports arm64 now.
